import type { StrategyStatements, Opportunity, Principle, StructuredProvocation } from '@/lib/types'

interface BriefData {
  projectName: string
  version: number
  generatedAt: string
  strategy: StrategyStatements
  fragmentCount: number
  syntheses: { dimension: string; confidence: string; fragmentCount: number }[]
  suggestedQuestions: StructuredProvocation[]
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

function confidenceIcon(confidence: string): string {
  switch (confidence) {
    case 'HIGH': return '●'
    case 'MEDIUM': return '◕'
    case 'LOW': return '◑'
    default: return '○'
  }
}

export function generateStrategicBrief(data: BriefData): string {
  const { strategy: s, projectName, version, generatedAt, fragmentCount, syntheses, suggestedQuestions } = data
  const lines: string[] = []

  lines.push(`# Strategic Brief — ${projectName}`)
  lines.push('')
  lines.push(`*Version ${version} · ${formatDate(generatedAt)} · Based on ${fragmentCount} strategic fragments*`)
  lines.push('')

  // Vision
  lines.push('## Vision')
  lines.push(s.vision)
  lines.push('')

  // Strategy
  lines.push('## Strategy')
  lines.push(s.strategy)
  lines.push('')

  // Objectives
  if (s.objectives?.length > 0) {
    lines.push('## Objectives')
    lines.push('')
    for (const obj of s.objectives) {
      const title = obj.title || obj.objective || obj.pithy || 'Untitled'
      const metric = obj.omtm ? ` — ${obj.omtm}` : ''
      const aspiration = obj.aspiration ? ` · ${obj.aspiration}` : ''
      lines.push(`### ${title}${metric}${aspiration}`)
      if (obj.explanation) {
        lines.push('')
        lines.push(obj.explanation)
      }
      lines.push('')
    }
  }

  // Principles
  if (s.principles?.length > 0) {
    lines.push('## Principles')
    lines.push('')
    for (const p of s.principles) {
      const priority = p.priority || p.title || ''
      const deprioritised = p.deprioritized || p.description || ''
      lines.push(`- **${priority}** even over ${deprioritised}`)
      if (p.context) {
        lines.push(`  ${p.context}`)
      }
    }
    lines.push('')
  }

  // Opportunities
  if (s.opportunities?.length > 0) {
    lines.push('## Opportunities')
    lines.push('')
    for (const opp of s.opportunities) {
      lines.push(`### ${opp.title}`)
      if (opp.description) lines.push(opp.description)
      if (opp.successMetrics?.length) {
        lines.push('')
        for (const m of opp.successMetrics) {
          if (m.belief) {
            lines.push(`We believe ${m.belief.action} will ${m.belief.outcome}`)
          }
          if (m.signal) {
            lines.push(`Signal: ${m.signal} · ${m.baseline || '?'} → ${m.target || '?'}`)
          }
        }
      }
      lines.push('')
    }
  }

  // Strategic Coverage
  if (syntheses.length > 0) {
    lines.push('## Strategic Coverage')
    lines.push('')
    for (const s of syntheses) {
      const label = s.dimension.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
      lines.push(`${confidenceIcon(s.confidence)} ${label} — ${s.fragmentCount} fragments`)
    }
    lines.push('')
  }

  // Open Questions
  if (suggestedQuestions.length > 0) {
    lines.push('## Open Questions')
    lines.push('')
    for (const q of suggestedQuestions) {
      lines.push(`- ${q.title || q.description}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('*Generated by Lunastak · app.lunastak.io*')

  return lines.join('\n')
}
