'use client';

import { useState, useEffect } from 'react';
import StrategyDisplay from '@/components/StrategyDisplay';
import { StrategyStatements } from '@/lib/types';

export default function DemoStrategyPage() {
  const [strategy, setStrategy] = useState<StrategyStatements | null>(null);
  const [thoughts, setThoughts] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchStrategy() {
      try {
        const response = await fetch('/api/demo/strategy');
        if (!response.ok) {
          throw new Error('Demo strategy not found');
        }
        const data = await response.json();
        setStrategy(data.output);
        setThoughts(data.claudeThoughts || '');
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load');
      } finally {
        setIsLoading(false);
      }
    }
    fetchStrategy();
  }, []);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-muted-foreground">Loading demo strategy...</div>
      </div>
    );
  }

  if (error || !strategy) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-destructive">Error: {error || 'No data'}</div>
      </div>
    );
  }

  return (
    <main className="min-h-screen bg-background">
      <div className="container mx-auto py-8">
        <div className="mb-6">
          <h1 className="text-2xl font-bold">Decision Stack Demo</h1>
          <p className="text-sm text-muted-foreground mt-1">
            A real strategy output generated by Luna
          </p>
        </div>
        <div className="max-w-6xl mx-auto">
          <StrategyDisplay
            strategy={strategy}
            conversationId="demo-conversation"
            traceId="demo-trace"
            projectId="demo-project"
          />
        </div>
        <div className="mt-8 border-t pt-6 text-center text-sm text-muted-foreground">
          <p>This is a real strategy generated from a Lunastak conversation.</p>
          <p className="mt-1">
            <a href="https://lunastak.io" className="text-primary hover:underline">
              Learn more about Lunastak
            </a>
          </p>
        </div>
      </div>
    </main>
  );
}
